version: "3.8"

services:
  server:
    build:
      context: .
    container_name: ai-fastapi-service
    environment:
      - ENVIRONMENT=production
    ports:
      - 8000:8000
    # command: ["sh", "-c", "fastapi dev app/main.py --host 0.0.0.0 --port 8000"]
    command: ["sh", "-c", "fastapi run app/main.py --host 0.0.0.0 --port 8000"]
    # volumes:
    #   - .:/app
